language: python

dist: bionic
sudo: false

python:
  - '3.5'
  - '3.6'

cache: pip

install:
  - pip install --quiet --requirement requirements.txt
  - pip install --quiet pylint pylint-django

script:
  - ./manage.py makemigrations && ./manage.py test -v1
  - pylint community fixtures fullcalendar home league openstudyroom search wgo manage.py

notifications:
  email:
    on_success: change
    on_failure: change
